services:
  web:
    build: .
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build/distributions:/etc/nginx/html
#    depends_on:
#      db:
#        condition: service_healthy
#  db:
#    image: postgres
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: ktor
#      POSTGRES_HOST_AUTH_METHOD: trust
#    ports:
#      - "54333:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1s